language: node_js
node_js: 
  - '13'

branches:
  only:
    - "master"
script:
  - cd client
  - npm ci
  - npm i -g eslint
  - npm run test-coverage
  - npm run eslint-report
  - cd ../backend
  - npm ci
  - npm run eslint-report
